### ISSUE TITLE
External Antenna Documentation

### ISSUE THREAD

**Issue by r3dfish** [LyndLabs/DNS-DriveBy#6]
I see the 5 hole cutout on the board for an external antenna, which I can see mounted in the following images:

https://lyndlabs.io/cdn/shop/files/dns-driveby-battery.jpg?v=1691353218&width=990
https://lyndlabs.io/cdn/shop/files/dns-driveby-computer.jpg?v=1691353218&width=990

but I don't see any documentation or even mention of the external antenna.  Can you please provide what hardware to use, and where/how to install the antenna?

Thanks

**Comment by lukeswitz** [comment]
It's confusing indeed. Ships with an ESP8266 D1 Mini, you **need a D1 Mini Pro** to attach an antenna via UFL > IPEX > SMA. 

There's no UFL to attach to on the D1. It's about $15 in parts for the upgrade to the Pro & SMA:
- Get [something like this](https://www.rfsupplier.com/ufl-ufl-ipx-ipex-to-sma-female-thru-holes-jack-right-angle-pcb-mount-rf-coaxial-cable-assembly-113mm-coax_p7390.html) but with 2.0mm not 1.3mm IPEX-
- Solder in place, generously for support.
- Replace the D1 > Pro and flash the image.

Not much to it, and FWIW I run them side-by-side and there is little difference.

**Comment by AlexLynd** [comment]
@r3dfish Hey!  I responded to this issue via email but it looks like it bounced.  

[I shot some pics & wrote some docs here.](https://dnsdriveby.com/guides/mods/external-antenna/).  Let me know if you have any other questions!  If you want to suggest future documentation, if you could leave an issue on the [docs repo](https://github.com/LyndLabs/dnsdriveby.com/) that'd be awesome :)

If you don't have any other questions, you can close out the issue.  Thanks for supporting the project!

- Alex
